Lesson 12
dimloko/freeit pull request #7
Opened 2020-09-23 19:48 UTC by dimloko

Homework for lesson_12

2020-10-08 17:47 UTC, TheFallen058 requested changes
well done. please check my notes

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/censorship/Censor.java
> +        String tmp = reader.readLine();
try not to use tmp as variable mane, it may be keyword in some cases

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/censorship/Censor.java
> +    private void readInputText(String inputTextName) throws IOException {
inputTextName - you do nothing with this arg, remove or check your logic

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/censorship/Censor.java
> +    public List<String> getBlackList() {
not sure that we need this getters

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/task34/IOTask34.java
> +        for (Integer number : numbers) { //Подсчёт суммы чисел
you can search and count in one cycle

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/task34/IOTask34.java
> +        while (count < numbers.size()) { //Удаление повторяющихся чисел
don't like cycle in cycle. how could we make it more efficient?

2020-10-08 17:47 UTC, TheFallen058 commented on lesson_12/src/task36/ListFolder.java
> +    static void list(File f, int level) {
One character variable names make me crazy((

2020-10-12 21:25 UTC, dimloko commented
> well done. please check my notes

Fixed lesson_12

2020-10-17 17:22 UTC, TheFallen058 approved these changes
done

2020-10-17 17:23 UTC, merged